apiVersion: v1
kind: Pod
metadata:
  name: some-memcached
  labels:
    name: some-memcached
spec:
  containers:
    - image: anakli/memcached:t1
      name: memcached
      resources:
        requests: 
          cpu: "0.5"
          memory: "32Mi"
        limits: 
          cpu: "0.75"
          memory: "64Mi"
      imagePullPolicy: Always
      command: ["/bin/sh"]
      args: ["-c", "taskset -c 0 ./memcached -t 1 -u memcache"]
  nodeSelector:
    cca-project-nodetype: "node-c-8core"


